### ISSUE TITLE
Can't set up correct bindings with oculus touch controllers

### ISSUE THREAD

**Issue by doyale** [nicoco007/DynamicOpenVR#13]
Problem:
When startign BeatSaber, the Controllers are just laying on the ground and can't be moved. They work in every other game. Trying to follow the troubleshooting guide worked out as follows:
The Controller Configuration for my controller wouldn't show up (stuck on loading), so i followed the steps to setup the correct binding. However, mapping the buttons as stated in the guide doesn't work since no options are showing up once I get to the action select menu.

**Comment by nicoco007** [comment]
I've heard a few other reports of the same thing. If you go into the DynamicOpenVR folder of your Beat Saber installation, there should be two folders, `Actions` and `Bindings`, a file called `action_manifest.json`, and a few other files under that. Could you share the file called `action_manifest.json` here?

**Comment by doyale** [comment]
Hello, thank you for taking a look at this issue. I have managed to reset everything in the meantime by hard resetting the Installation, but i still couldn’t get DynamicOpenVR to work sadly. I have attached the file you asked for here. Kind regardsL. StarkVon: Nicolas GnyraGesendet: Samstag, 25. Januar 2020 22:47An: nicoco007/DynamicOpenVRCc: doyale; AuthorBetreff: Re: [nicoco007/DynamicOpenVR] Can't set up correct bindings with oculus touch controllers (#13) I've heard a few other reports of the same thing. If you go into the DynamicOpenVR folder of your Beat Saber installation, there should be two folders, Actions and Bindings, a file called action_manifest.json, and a few other files under that. Could you share the file called action_manifest.json here?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Dingaling101** [comment]
Hi, I had the same issue but i wrote -vrmode oculus in the luanch options and it worked for me!

**Comment by nicoco007** [comment]
Unfortunately it doesn't look like the file attached properly. Could you do it through GitHub instead? You might also need to put it in a ZIP file.
