### ISSUE TITLE
As soon as I select an avatar my triggers stop working 

### ISSUE THREAD

**Issue by strixr** [nicoco007/DynamicOpenVR#16]
Once I go into the avatar mod menu and select an avatar the triggers stop working and I can select any options in beat saber. 

I've tried making a custom binding but it still doesn't seem to fix this issue.

Any help would be great thanks.

[Logs.zip](https://github.com/nicoco007/DynamicOpenVR/files/4162385/Logs.zip)

**Comment by nicoco007** [comment]
Before going any further, I have a few questions:
* Just to clarify - it's just the triggers that stop working, not tracking of the hands?
* When you press the triggers alternating from one controller to the other, does the blue laser thing coming out of the sabers switch from one controller to the other or is it stuck on just one of them?
* What controllers are you using?
* Does this happen for all avatars or just specific one(s)?

**Comment by strixr** [comment]
Yea I had the problem where it was just t-posing but managed to sort that issue out yesterday.
So

- Hands still track but I cant seem to select anything in game. I tried binding right trigger pull to another button but that didnt work 

- Blue laser is stuck in one hand and cant switch. The menu icons still highlight when I point at them.

- Using htc vive controllers

- It seems to be any avatar. Just selected the template avatar today and as soon as I did I couldnt select anything else. Happened with a custom one before but I deleted everything and reinstalled and tried it with the default template and it breaks the input

I just deleted the avatar from the install folder and everything works again

**Comment by nicoco007** [comment]
When you get the chance, could you try out this version of DynamicOpenVR and post logs again?

[DynamicOpenVR.BeatSaber-b86f25b-RELEASE.zip](https://github.com/nicoco007/DynamicOpenVR/files/4162491/DynamicOpenVR.BeatSaber-b86f25b-RELEASE.zip)

**Comment by strixr** [comment]
Ok yea that seems to have fixed it. Can get into the menus and switch between any of the custom avatars I have!

I followed your how to guide on completely removing DynamicOpenVR just to make sure aswell.

Thanks so much for your help.
[Logs.zip](https://github.com/nicoco007/DynamicOpenVR/files/4162506/Logs.zip)

**Comment by nicoco007** [comment]
Great! I'll close this issue now since it looks like everything's working but feel free to open a new one if you run into any other problems.
