### ISSUE TITLE
not finding the code for the binding

### ISSUE THREAD

**Issue by sixelFTW** [nicoco007/DynamicOpenVR#18]
i was trying to find the code on the steamvr.vrsettings but the code "steam.app.620980 doesnt show up at all. the link here will show you what all it shows 
![steamvr copy pdf - Notepad 2_11_2020 1_45_03 AM](https://user-images.githubusercontent.com/60915544/74218669-37891400-4c70-11ea-9f07-31bf9a52564b.png)

**Comment by nicoco007** [comment]
If it doesn't show up in the file, then you can ignore that section of the troubleshooting guide.
