### ISSUE TITLE
-vrmode Oculus Supprt

### ISSUE THREAD

**Issue by balu100** [nicoco007/DynamicOpenVR#2]
Hey,

I wanted to try out the new custom avatars (which seems to be Awesome!), but unfortunately when i try to open Beat Saber with -vrmode oculus my avatar stuck in the default position, and my separatly moving menu sabers cannot click anything even tho they can move.

**Comment by nicoco007** [comment]
That's odd. Is SteamVR running at all when this problem occurs? Could you also attach your latest log (usually located at `Logs\_latest.log` in your Beat Saber installation folder) ?
