### ISSUE TITLE
Trigger not working when taking off HMD and putting it on again

### ISSUE THREAD

**Issue by fuyushi** [nicoco007/DynamicOpenVR#25]
[_latest - Copy.log](https://github.com/nicoco007/DynamicOpenVR/files/4294493/_latest.-.Copy.log)

- Operating system: Windows 10
- Headset and controllers: Oculus rift [CV1]

Started the game without having the headset on, went into solo play and start a song whilst holding my finger over the hmd proximity sensor (to get controller buttons usable). 
When after a few seconds I tried putting on the headset and in the pause screen I noticed that even though the controllers are tracking, I cannot use the trigger button to for example go back to the main menu. Notice that also the laser pointer is gone (both things work in the Oculus and Steam overlay though). 
The button to pause/unpause however still works. 

Aside from that, from my experience there is a chance when taking off the headset, and putting it on again that this exact issue may occur. So I assume it has something to do with the headset and controllers going to idle and not cominig back properly or so.

**Comment by nicoco007** [comment]
Yeah, I noticed a similar issue causing the triggers to stop working when opening/closing the SteamVR overlay. I'm guessing the cause is the same, and I'm looking into it.

**Comment by nicoco007** [comment]
If you're still running into this issue, these builds of [DynamicOpenVR](https://ci.gnyra.com/job/DynamicOpenVR/job/master/165/artifact/DynamicOpenVR-10a4b64-RELEASE.zip) and [DynamicOpenVR.BeatSaber](https://ci.gnyra.com/job/DynamicOpenVR/job/master/165/artifact/DynamicOpenVR.BeatSaber-10a4b64-RELEASE.zip) should fix it.

**Comment by nicoco007** [comment]
If you're still running into this issue, these builds of [DynamicOpenVR](https://ci.gnyra.com/job/DynamicOpenVR/job/master/168/artifact/DynamicOpenVR-b565556-RELEASE.zip) and [DynamicOpenVR.BeatSaber](https://ci.gnyra.com/job/DynamicOpenVR/job/master/168/artifact/DynamicOpenVR.BeatSaber-b565556-RELEASE.zip) should fix it.

**Comment by LYNXVIP3R** [comment]
im having the same problem with my oculus quest 2 triggers not working
