### ISSUE TITLE
Bindings stop working when selecting custom character - SOLVED

### ISSUE THREAD

**Issue by king-pavo** [nicoco007/DynamicOpenVR#26]
hey, thanks for the mod
 I use the index controllers and beatsaber version 1.7.0.

my bindings stop working when I select a custom char in beatsaber and I tried your troubleshooting guide but everything I tried did not work.

I attached my working binding export and the not working one

[input-not working.zip](https://github.com/nicoco007/DynamicOpenVR/files/4346303/input-not.working.zip)
[input-working.zip](https://github.com/nicoco007/DynamicOpenVR/files/4346304/input-working.zip)

Additionally my log file and the json files:
[DynamicOpenVR.zip](https://github.com/nicoco007/DynamicOpenVR/files/4350216/DynamicOpenVR.zip)
[_latest.zip](https://github.com/nicoco007/DynamicOpenVR/files/4350218/_latest.zip)

Also, knuckles finger tracking works, it´s obviously useless in this game but nice that it works and if I delete dynamicopenvr the custom chars disappear.

**Comment by RowanVastia** [comment]
Same problem 
[custom Avatar.zip](https://github.com/nicoco007/DynamicOpenVR/files/4357539/custom.Avatar.zip)

**Comment by RowanVastia** [comment]
hey just got custom avatar to work with index controller using this file.
[DynamicOpenVR.BeatSaber-b86f25b-RELEASE.zip](https://github.com/nicoco007/DynamicOpenVR/files/4363100/DynamicOpenVR.BeatSaber-b86f25b-RELEASE.zip)

**Comment by nicoco007** [comment]
Yeah, that's a known issue. You can try what @ZeSanvx12 posted and if that doesn't work, you can try the latest unstable builds which should fix the issue; you'll need [Custom Avatars](https://ci.gnyra.com/job/BeatSaberCustomAvatars/job/develop/98/artifact/BeatSaberCustomAvatars-d7f5bc4-RELEASE.zip), [DynamicOpenVR](https://ci.gnyra.com/job/DynamicOpenVR/job/master/132/artifact/DynamicOpenVR-5fd09c6-RELEASE.zip), and [DynamicOpenVR.BeatSaber](https://ci.gnyra.com/job/DynamicOpenVR/job/master/132/artifact/DynamicOpenVR.BeatSaber-5fd09c6-RELEASE.zip). If you're still having issues with the latest builds, try deleting the `DynamicOpenVR.BeatSaber.dll` file in the `Plugins` folder.

**Comment by king-pavo** [comment]
thx for the reply, I got it to work! it works like it should by injecting revive 1.9.2. thx for your awesome work
