### ISSUE TITLE
Avatars do not work with newest Beat saber version

### ISSUE THREAD

**Issue by EnnaelK3219** [nicoco007/DynamicOpenVR#27]
after going step by step in the instruction guide, and making sure all avatar files were properly placed, the game REGISTERS the avatar mod as active, but I turn around to check my CameraPlus, which has always shown avatars before, and lo and behold, no avatar.  I check the avatar list, and sure enough, I have my avatar selected.

All CustomAvatars and DynamicOpenVR files are in the proper places, so I fail to see how this went wrong...  It registered EVERY OTHER MOD just fine, but avatars it has an issue with.

I have tried to ask the (Beat Saber Modding) Discord for help, but got no responses for days.  I even tried asking again before sending this, and got no response.

**Comment by nicoco007** [comment]
Can you see your avatar in the mirror when in the Avatars menu? Also, could you attach your latest log?

**Comment by EnnaelK3219** [comment]
No avatars show in the mirror, or in the camera.
    On Saturday, March 21, 2020, 10:13:22 PM EDT, Nicolas Gnyra <notifications@github.com> wrote:  
 
 


Can you see your avatar in the mirror when in the Avatars menu? Also, could you attach your latest log?

**Comment by EnnaelK3219** [comment]
[_latest.log](https://github.com/nicoco007/DynamicOpenVR/files/4365984/_latest.log)

No avatars show in the mirror.  It reverts to the "No Avatar" state.

**Comment by EnnaelK3219** [comment]
Looking back through the changelog you provided, you said you "hardcoded the No Avatar" option.  Maybe you hardcoded it so much that no other avatar will show?

**Comment by nicoco007** [comment]
Hey! Sorry I haven't answered, I somehow managed to completely forget about this issue. Is this still a problem when running Beat Saber 1.9.0 with [Custom Avatars 5.0.0-beta.7](https://github.com/nicoco007/BeatSaberCustomAvatars/releases/tag/v5.0.0-beta.7) and [DynamicOpenVR 0.2.0](https://github.com/nicoco007/DynamicOpenVR/releases/tag/v0.2.0)?
