### ISSUE TITLE
I cannot play beat saber anymore.

### ISSUE THREAD

**Issue by SpoonMcForky** [nicoco007/DynamicOpenVR#28]
I had DOVR, and then the newest update deleted my plugins and I couldn't get them to work again, so I just downloaded songs and wanted to play them with no plugins. Well, I get into the game, and my Rift S controllers' triggers do not work in beat saber. I've reset steam vr default settings, uninstalled steam vr, uninstalled beat saber, and dleeted any trace of DOVR from my computer. Apparently this is a known glitch and the fix is just deleting the files, obviously that didn't work.

**Comment by SpoonMcForky** [comment]
hello?

**Comment by nicoco007** [comment]
Hey, I'm really sorry for taking so long to answer; I've been really busy with external things beyond my control. I hope you were able to find the solution on your own. If you haven't, I have a few suggestions:

* Double-check to make sure you've deleted the files listed in the [troubleshooting guide](https://github.com/nicoco007/DynamicOpenVR/blob/master/TROUBLESHOOTING.md#completely-removing-dynamicopenvr).
* Close Steam & SteamVR and delete the `appconfig.json`, `steamapps.vrmanifest`, and `steamvr.vrsettings` files inside the `config` folder of your Steam installation (they will appear as just `appconfig`, `steamapps`, and `steamvr` if you don't have extensions visible). They contain information about input bindings so getting rid of them should hopefully fix your issue.

If doing that doesn't solve the issue, I'm unfortunately not sure what to tell you. The files listed in the troubleshooting guide and the 3 listed above cover everything that DynamicOpenVR touches. I'll do my best to help you out if you're still having problems, though.

**Comment by Marshymallowy** [comment]
Hi I suggest you do a proper [clean install](https://bsmg.wiki/support#clean-installation) of the game
and if that doesnt work then try
deleting [beatsabers appdataI](https://bsmg.wiki/support/#deleting-your-save-in-appdata)
if it doesn't work then please reply to this topic.
