### ISSUE TITLE
Controller buttons wont work

### ISSUE THREAD

**Issue by ArcStalker** [nicoco007/DynamicOpenVR#31]
[2020.05.11.19.28.53.log.gz](https://github.com/nicoco007/DynamicOpenVR/files/4611061/2020.05.11.19.28.53.log.gz)

Windows 10
Headset and controllers - Oculus rift s

My controller buttons wont work when beat saber started. pointing laser attached to right hand and wont switch ether. cant even pass first menu with continue button. oculus menu and steam menu buttons still properly working. controllers still tracking properly

also i noticed on my pc screen that my usual avatar just disappeared, and there just usual 2 floating in air controllers
![image](https://user-images.githubusercontent.com/65185097/81591614-5f9a2780-93c5-11ea-953c-5b01515435f7.png)

last time i playing without any issues (about 2 weeks ago) im sure it somehow connected to another bsaber update

**Comment by Cyrox94** [comment]
Check your DynamicVr, Lib, and Plugin files the new update removed those files once i put them back in the game worked fine again

**Comment by ArcStalker** [comment]
oww, i thought i looked everything in troubleshooting how to fix that, checked suggested files 
for availability, all mentioned files was on their places. so i just reinstall dynamic open vr, bsaber dynamic open vr and custom avatars, and now all work again completely fine.
