### ISSUE TITLE
Support for Windows Mixed Reality controllers

### ISSUE THREAD

**Issue by Sarayalth** [nicoco007/DynamicOpenVR#4]
After following the troubleshooting guide everything works now and this is the file with the input bindings

GitHub doesn't support json files in issues, so I just zipped it
[steam_app_620980_binding_holographic_controller.zip](https://github.com/nicoco007/DynamicOpenVR/files/3999642/steam_app_620980_binding_holographic_controller.zip)

**Comment by nicoco007** [comment]
Thanks for your help! I'll make sure to include this in the next release.

**Comment by nicoco007** [comment]
This was added in commit 6af1a0a and will be included in the next release.
