### ISSUE TITLE
Oculus Touch

### ISSUE THREAD

**Issue by Zro-san** [nicoco007/DynamicOpenVR#5]
I need help for the Oculus Touch Controlers I dont check that.

**Comment by Zro-san** [comment]
I cant play Beat Saber anymore because this shit mod thx

**Comment by nicoco007** [comment]
I'm going to need more information to help you out.
* Are you using SteamVR's or Oculus' tracking?
* Are you using the latest beta of both [DynamicOpenVR](https://github.com/nicoco007/DynamicOpenVR/releases/tag/v0.1.0-beta.4) and [Custom Avatars](https://github.com/nicoco007/BeatSaberCustomAvatars/releases/tag/v5.0.0-beta.4) (beta 4)?
* Could you please attach your latest log (the `_latest.log` file from the `Logs` folder in your Beat Saber installation folder)?
