### ISSUE TITLE
Vivie pro, binding problem.

### ISSUE THREAD

**Issue by Leagionvoid** [nicoco007/DynamicOpenVR#6]
Hello great work btw i followed a guide from Elite Eric and everything seems to run smoothely except that the controllers are now stuck to the ground. when i go to controllerbindings and try to make custom binding i dont get the option to put left hand trigger. only option is none as in the guide after you hit trigger,add, and on the pull.........(none) click it for more options i have blank(Vector1 Action) and only none to click on, Even tried presaving bindings but they show as clear when i try them too. Any insight or help would be much appreciated. Edit. Also aftre wiping beatsaber several times and doing it from scratch i have also gotten the option of default bindings but it wont work even then, (Edit) i found out that its the Folder (Libs) that contains(DynamicOpenVR.dll) that seems to be my problem. i have added every other document that im supposed to but once i add that my controllers stops regestring and drops to floor.

**Comment by nicoco007** [comment]
That's strange. It's probably a mistake on my end that's causing this issue; I'll take a look ASAP.

Are you using the Vive Pro's wand controllers or something else?

**Comment by Leagionvoid** [comment]
Hello, thank you for taking your time to help me. I kida obsess when something does not work so i found a solution, dont really know how it would make a diffrence but i tokk all files from both zip files and dragged them into beatsaberfolder even though som of them duplicate/overrides on another as to how Elite eric handpicked from thoese zip files. and it worked! really pleased with the mods, great preformence and no problems after so thank you.

________________________________
Fra: Nicolas Gnyra <notifications@github.com>
Sendt: torsdag 2. januar 2020 02:15
Til: nicoco007/DynamicOpenVR <DynamicOpenVR@noreply.github.com>
Kopi: Leagionvoid <mads-johannessen@hotmail.com>; Author <author@noreply.github.com>
Emne: Re: [nicoco007/DynamicOpenVR] Vivie pro, binding problem. (#6)


That's strange. It's probably a mistake on my end that's causing this issue; I'll take a look ASAP.

Are you using the Vive Pro's wand controllers or something else?
