### ISSUE TITLE
Oculus Touch Tracking Issue.

### ISSUE THREAD

**Issue by the-luxz** [nicoco007/DynamicOpenVR#7]
Hello! First off I'd like to say that I really do appreciate what your mod brings to the table in terms of entertainment. 

Now time for the issue at hand. I have recently tried to install and use your mod, however every time I reinstall or re download the game and verify files of beat saber itself I have the same common issue. That is that my beat saber bindings are not properly set. I look down to find the lightsabers just sitting there. Doing nothing, I looked at your trouble shooting guide and I found nothing that could help me with this issue. I also have the newest files downloaded. DynamicOpenVR. Hence these links, for what I am trying to do.

https://github.com/nicoco007/DynamicOpenVR/releases/tag/v0.1.0-beta.4
https://github.com/nicoco007/BeatSaberCustomAvatars/releases/tag/v5.0.0-beta.4

Finally I am using SteamVR's tracking. I will also be leaving my latest log from beatsaber as well for your convince. 

Regards, 
- Luxz

My _lastest log file can be found here: https://drive.google.com/file/d/1RFQ0_vaOgeftiX-W8Y4Gl_YHQnA4azgV/view?usp=sharing 

Sorry I can't attack the file as it is larger than 10MB.

**Comment by FLORALTV** [comment]
hey my guy, i found a solution for that if your still stuck. right click on beat saber in steam and go to properties. then click on the set launch options button. after that type into it "-vrmode oculus" then try running beat saber
tell me how it goes if you havent figured it out already

**Comment by onefast33** [comment]
so when I'm in the edit controller bindings in steam VR and click on beat saber nothing shows up

**Comment by FLORALTV** [comment]
add me on discord and ill try to walk you through it FLORALTV#5391

**Comment by nicoco007** [comment]
If you're still having this issue, I suggest first trying the latest versions of both Custom Avatars and DynamicOpenVR. If that still doesn't work, you can also try using native Oculus tracking instead of SteamVR by adding `-vrmode oculus` to Beat Saber's startup options (right click on Beat Saber > Properties > Set launch options > Type `-vrmode oculus` in the box).

I'm working on adding more information to the troubleshooting guide so hopefully next time you give it a try it'll work properly.

**Comment by killzoms** [comment]
I can confirm with the latest Pre-Release version that Both Custom Avatars and DynamicOpenVR work on the Oculus Touch. Had to copy DynamicOpenVR release over last due to some changes that did not get pushed to Custom Avatars.
