### ISSUE TITLE
HTC Vive bindings Issue, Unable to play Beat Saber

### ISSUE THREAD

**Issue by zahairaj** [nicoco007/DynamicOpenVR#8]
After following your troubleshooting, when I went to add pull on the controllers, I could only add none. After I couldn't solve the problem to this I decided to just Unistall DynamicOpenVR from BeatSaber. The issue now is that I can't remove that binding that I tried to make and I can't select or play beat saber anymore. Please tell me the answer to this problem as now I cannot play the game.
![image](https://user-images.githubusercontent.com/59424654/71648422-fba67a80-2cd1-11ea-894d-79d5d14a85a8.png)

**Comment by nicoco007** [comment]
I'm really sorry you're having issues. There should be default bindings for the Vive controllers so I'm a bit confused as to why that's not working; I'll have to take a look at that.

For now, following the instructions under [Completely Removing DynamicOpenVR](https://github.com/nicoco007/DynamicOpenVR/blob/master/TROUBLESHOOTING.md#3-completely-removing-dynamicopenvr) should help with broken bindings after uninstalling. Let me know if you still have issues after removing all the files/folders listed there.

**Comment by zahairaj** [comment]
I have removed all of the files listed and the issue still persists. I am able to move my controllers but, such but as in interacting and clicking buttons in-game nothing works. Would completely uninstalling BeatSaber fix the problem?

**Comment by Leagionvoid** [comment]
Hi IV0idI23, yes if you go to steam and uninstall the game, but also go to the folder where it is stored. you can easely find it by clicing on settings when you are in your liberary, clicked on beatsaber and show local files. only thing you have to be aware of is to copy your custom songs,avatars, sabers platforms etc that you dont want to lose before you deleate the entire beatsaberfolder. all achivements and progress on oficcial songs is saved in steamcloud. and should be saved in custom songs if u as mentioned earlier save the custom songs folder. then reinstall the game. play it. close it. open mod assistant update and install. and then drag back the custom song in the beatsaber/customsongs folder. and you should be back to default. if i explained poorly you can check out "EliteErick" on youtube that explains it. and the fix on my own problems you can check out    https://www.youtube.com/watch?v=JrVAoaEa0R8 .

**Comment by zahairaj** [comment]
Thank you Leagionvoid, This worked well for me. With the avatars, I'm still unable to bind them and get it to work but as of now, I'm fine without them.

**Comment by danivastus** [comment]
Hello, I'm having the same issue, was wondering if there is any update on this?

**Comment by danivastus** [comment]
I have fixed my issue, I watched youtube video by "EliteErick" and only used the custom avatars portion of dynamic open VR and didn't use the "bindings" folder in the dedicated dynamic open VR folder. I have all the bindings I need. :)

**Comment by nicoco007** [comment]
I'm going to close this issue since the question seems to have been answered. If at some point you would like to try installing Custom Avatars again and still run into issues, please open a new issue.
