### ISSUE TITLE
None of my button inputs are working beforew the controllers were stuck to the ground but i fixed it

### ISSUE THREAD

**Issue by pooboy69** [nicoco007/DynamicOpenVR#9]

**Comment by CoffeeIsLife87** [comment]
how did you fix the controllers on the ground?

**Comment by nicoco007** [comment]
I'm not sure what is going on here. If you'd like to share your solution, I suggest you do it [on the Beat Saber Modding Group Discord server](https://discord.gg/beatsabermods). If you have an ongoing problem with the mod, feel free to open another issue and describe in detail what's not working.
